name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Start local MinIO server
      run: docker run -d -p 9000:9000 --name minio minio/minio server /data

    - name: Bootstrap MinIO server
      run: script/bootstrap-minio minio

    - name: Test
      run: go test -v ./...

  build-support-images:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file: [dummy, volume-extractor]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: support-containers
        push: true
        file: support-containers/${{ matrix.file }}.dockerfile
        tags: cocov/${{ matrix.file }}:v0.1
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
